# Dataset
train_db_name: VOCSegmentationDistill
train_db_kwargs:
   split: trainaug
   batch_size: 16
   transforms: fblib_pascal
   distill_dir: outputs/predictions/multi_obj_avg/ # path to generated labels
val_db_name: VOCSegmentation
val_db_kwargs:
   batch_size: 16
   transforms: fblib_pascal
num_workers: 4

# Model
backbone: 'resnet50'
model_kwargs:
  pretraining: 'moco'
  pretraining_path: pretrained/moco.pth.tar
  use_fcn: False
loss: ohem
loss_kwargs:
  threshold: 0.2

# Optimizer
epochs: 45
scheduler: step
scheduler_kwargs:
   lr_decay_rate: 0.1
   lr_decay_epochs: [40]

optimizer: sgd 
optimizer_kwargs:
   lr: 0.002
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False

freeze_batchnorm: 'none'
freeze_layers: 2
